try:
    x/0
except:
    print('Error found')